"""reconcile schema drift with current models

Revision ID: a8bf7eb4833c
Revises: 0009
Create Date: 2026-07-28 14:58:35.653399
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a8bf7eb4833c'
down_revision = '0009'
branch_labels = None
depends_on = None


_MUTATION_CLASSIFICATION = postgresql.ENUM(
    'pathogenic', 'likely_pathogenic', 'uncertain', 'likely_benign', 'benign',
    name='mutationclassification',
)
_ONCOKB_LEVEL = postgresql.ENUM(
    'level_1', 'level_2', 'level_3a', 'level_3b', 'level_4', 'r1', 'r2', 'unknown',
    name='oncokblevel',
)
_ORDER_STATUS = postgresql.ENUM(
    'pending', 'payment_processing', 'confirmed', 'failed', 'manufacturing',
    'shipped', 'delivered', 'cancelled',
    name='orderstatus',
)
_SUBMISSION_STATUS = postgresql.ENUM(
    'queued', 'processing', 'awaiting_ai', 'complete', 'failed',
    name='submissionstatus',
)


def upgrade() -> None:
    # These 4 enum types are new (bidstatus/discoverystatus already exist from
    # earlier migrations). SQLAlchemy's inline `sa.Enum(...)` in add_column /
    # alter_column does not reliably auto-CREATE TYPE outside of create_table,
    # so create them explicitly first (checkfirst=True is a no-op if already
    # present, making this migration safe to re-run).
    bind = op.get_bind()
    _MUTATION_CLASSIFICATION.create(bind, checkfirst=True)
    _ONCOKB_LEVEL.create(bind, checkfirst=True)
    _ORDER_STATUS.create(bind, checkfirst=True)
    _SUBMISSION_STATUS.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_repurposing_submission_id', table_name='repurposing_candidates')
    op.drop_table('repurposing_candidates')
    op.alter_column('campaigns', 'raised_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('campaigns', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('campaigns', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('campaigns', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint('campaigns_result_id_key', 'campaigns', ['result_id'])
    op.drop_constraint('campaigns_patient_id_fkey', 'campaigns', type_='foreignkey')
    op.drop_constraint('campaigns_submission_id_fkey', 'campaigns', type_='foreignkey')
    op.create_foreign_key('campaigns_order_id_fkey', 'campaigns', 'orders', ['order_id'], ['id'])
    op.create_foreign_key('campaigns_patient_id_fkey', 'campaigns', 'patients', ['patient_id'], ['id'])
    op.create_foreign_key('campaigns_result_id_fkey', 'campaigns', 'results', ['result_id'], ['id'])
    op.drop_column('campaigns', 'percent_complete')
    op.drop_column('campaigns', 'submission_id')
    op.drop_column('campaigns', 'stripe_product_id')
    op.alter_column('cohort_mutations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index('ix_cohort_mutations_gene', table_name='cohort_mutations')
    op.drop_index('ix_cohort_mutations_gene_protein', table_name='cohort_mutations')
    op.drop_index('ix_cohort_mutations_study_id', table_name='cohort_mutations')
    op.alter_column('cohort_samples', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index('ix_cohort_samples_sample_id', table_name='cohort_samples')
    op.drop_index('ix_cohort_samples_study_id', table_name='cohort_samples')
    op.alter_column('copy_number_alterations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index('ix_cna_gene', table_name='copy_number_alterations')
    op.drop_index('ix_cna_submission_id', table_name='copy_number_alterations')
    op.alter_column('deletion_requests', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('deletion_requests', 'patient_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_foreign_key('deletion_requests_patient_id_fkey', 'deletion_requests', 'patients', ['patient_id'], ['id'], ondelete='SET NULL')
    op.alter_column('drug_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('mutation_signatures', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index('ix_sig_submission_id', table_name='mutation_signatures')
    # server_default required: existing rows need a value for this NOT NULL
    # column at ALTER TABLE time. "uncertain" matches the model's Python-side
    # ORM default (models/mutation.py) for the semantically-unknown case.
    op.add_column('mutations', sa.Column(
        'classification',
        _MUTATION_CLASSIFICATION,
        nullable=False,
        server_default='uncertain',
    ))
    op.add_column('mutations', sa.Column('clinvar_id', sa.String(length=64), nullable=True))
    op.add_column('mutations', sa.Column('cosmic_id', sa.String(length=64), nullable=True))
    op.alter_column('mutations', 'gene',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # Coalesce NULL to 'unknown' (the model's default, models/mutation.py)
    # before casting, so this is safe even if existing rows have NULL.
    op.alter_column('mutations', 'oncokb_level',
               existing_type=sa.VARCHAR(),
               type_=_ONCOKB_LEVEL,
               postgresql_using="coalesce(oncokb_level, 'unknown')::oncokblevel",
               nullable=False)
    op.alter_column('mutations', 'is_targetable',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('mutations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index('ix_mutations_gene', table_name='mutations')
    op.drop_index('ix_mutations_submission_id', table_name='mutations')
    op.drop_constraint('mutations_submission_id_fkey', 'mutations', type_='foreignkey')
    op.create_foreign_key('mutations_submission_id_fkey', 'mutations', 'submissions', ['submission_id'], ['id'])
    op.drop_column('mutations', 'hgvs_p')
    op.drop_column('mutations', 'consequence')
    op.drop_column('mutations', 'clinvar_significance')
    op.drop_column('mutations', 'civic_evidence')
    op.drop_column('mutations', 'variant')
    op.drop_column('mutations', 'alphamissense_class')
    op.drop_column('mutations', 'hgvs_c')
    op.add_column('oncologists', sa.Column('specialty', sa.String(length=128), nullable=True))
    # server_default=0 required for existing rows (model default is 0).
    op.add_column('oncologists', sa.Column('reports_reviewed', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('oncologists', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('oncologists', 'verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('oncologists', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('orders', 'drug_spec',
               existing_type=sa.TEXT(),
               nullable=False)
    # Same class of issue as migration 0006's is_open fix: the existing
    # VARCHAR server_default cannot be implicitly cast to the new enum type in
    # one ALTER COLUMN TYPE step. Drop the old default, retype, reapply.
    op.alter_column('orders', 'status', existing_type=sa.VARCHAR(), server_default=None)
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(),
               type_=_ORDER_STATUS,
               postgresql_using="coalesce(status, 'pending')::orderstatus",
               nullable=False)
    op.alter_column('orders', 'status', existing_type=_ORDER_STATUS, server_default='pending')
    op.alter_column('orders', 'amount_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('orders_patient_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key('orders_patient_id_fkey', 'orders', 'patients', ['patient_id'], ['id'])
    op.drop_column('orders', 'stripe_pi_id')
    op.drop_column('orders', 'drug_name')
    op.alter_column('patients', 'consent_research_sharing',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('patients', 'data_retention_days',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('365'))
    op.alter_column('patients', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint('patients_email_hash_key', 'patients', ['email_hash'])
    op.drop_column('patients', 'consent_given')
    op.alter_column('pharma_bids', 'status',
               existing_type=postgresql.ENUM('open', 'accepted', 'rejected', 'expired', name='bidstatus'),
               nullable=False,
               existing_server_default=sa.text("'open'::bidstatus"))
    op.alter_column('pharma_bids', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('pharma_companies', 'country',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('pharma_companies', 'contact_email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('pharma_companies', 'verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('pharma_companies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('pharma_companies', 'logo_url')
    op.alter_column('repurposing', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('results', sa.Column('oncologist_id', sa.String(), nullable=True))
    op.alter_column('results', 'has_targetable_mutation',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('results', 'oncologist_reviewed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('results', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('results_submission_id_fkey', 'results', type_='foreignkey')
    op.create_foreign_key('results_oncologist_id_fkey', 'results', 'oncologists', ['oncologist_id'], ['id'])
    op.create_foreign_key('results_submission_id_fkey', 'results', 'submissions', ['submission_id'], ['id'])
    op.drop_column('results', 'summary')
    op.drop_column('results', 'report_url')
    op.alter_column('rnaseq_expression', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index('ix_rnaseq_gene', table_name='rnaseq_expression')
    op.drop_index('ix_rnaseq_submission_id', table_name='rnaseq_expression')
    op.alter_column('structural_variants', 'sv_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('structural_variants', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index('ix_sv_gene1', table_name='structural_variants')
    op.drop_index('ix_sv_submission_id', table_name='structural_variants')
    op.alter_column('studies', 'sample_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('studies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index('ix_studies_cancer_type', table_name='studies')
    op.drop_index('ix_studies_study_id', table_name='studies')
    op.alter_column('submissions', 'cancer_type',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    # Same server_default cast issue as orders.status above.
    op.alter_column('submissions', 'status', existing_type=sa.VARCHAR(), server_default=None)
    op.alter_column('submissions', 'status',
               existing_type=sa.VARCHAR(),
               type_=_SUBMISSION_STATUS,
               postgresql_using='status::submissionstatus',
               existing_nullable=False)
    op.alter_column('submissions', 'status', existing_type=_SUBMISSION_STATUS, server_default='queued')
    op.alter_column('submissions', 'submitted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index('ix_submissions_patient_id', table_name='submissions')
    op.drop_index('ix_submissions_status', table_name='submissions')
    op.drop_constraint('submissions_patient_id_fkey', 'submissions', type_='foreignkey')
    op.create_foreign_key('submissions_patient_id_fkey', 'submissions', 'patients', ['patient_id'], ['id'])
    op.drop_column('submissions', 'dna_key')
    op.drop_column('submissions', 'biopsy_key')
    op.drop_column('submissions', 'vcf_key')
    op.drop_column('submissions', 'report_key')
    op.drop_column('submissions', 'updated_at')
    op.drop_column('submissions', 'created_at')
    op.drop_column('submissions', 'error_message')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('submissions', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('submissions', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('submissions', sa.Column('report_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('submissions', sa.Column('vcf_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('submissions', sa.Column('biopsy_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('submissions', sa.Column('dna_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('submissions_patient_id_fkey', 'submissions', type_='foreignkey')
    op.create_foreign_key('submissions_patient_id_fkey', 'submissions', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_submissions_status', 'submissions', ['status'], unique=False)
    op.create_index('ix_submissions_patient_id', 'submissions', ['patient_id'], unique=False)
    op.alter_column('submissions', 'submitted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # Drop the enum-typed default before retyping (mirrors the upgrade() fix);
    # otherwise the enum type can't be dropped later (dependent default).
    op.alter_column('submissions', 'status', existing_type=_SUBMISSION_STATUS, server_default=None)
    op.alter_column('submissions', 'status',
               existing_type=_SUBMISSION_STATUS,
               type_=sa.VARCHAR(),
               postgresql_using='status::varchar',
               existing_nullable=False)
    op.alter_column('submissions', 'status', existing_type=sa.VARCHAR(), server_default=sa.text("'queued'::character varying"))
    op.alter_column('submissions', 'cancer_type',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.create_index('ix_studies_study_id', 'studies', ['study_id'], unique=False)
    op.create_index('ix_studies_cancer_type', 'studies', ['cancer_type'], unique=False)
    op.alter_column('studies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('studies', 'sample_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_index('ix_sv_submission_id', 'structural_variants', ['submission_id'], unique=False)
    op.create_index('ix_sv_gene1', 'structural_variants', ['gene1'], unique=False)
    op.alter_column('structural_variants', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('structural_variants', 'sv_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_index('ix_rnaseq_submission_id', 'rnaseq_expression', ['submission_id'], unique=False)
    op.create_index('ix_rnaseq_gene', 'rnaseq_expression', ['gene'], unique=False)
    op.alter_column('rnaseq_expression', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('results', sa.Column('report_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint('results_oncologist_id_fkey', 'results', type_='foreignkey')
    op.drop_constraint('results_submission_id_fkey', 'results', type_='foreignkey')
    op.create_foreign_key('results_submission_id_fkey', 'results', 'submissions', ['submission_id'], ['id'], ondelete='CASCADE')
    op.alter_column('results', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('results', 'oncologist_reviewed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('results', 'has_targetable_mutation',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('results', 'oncologist_id')
    op.alter_column('repurposing', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('pharma_companies', sa.Column('logo_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('pharma_companies', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('pharma_companies', 'verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('pharma_companies', 'contact_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('pharma_companies', 'country',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('pharma_bids', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('pharma_bids', 'status',
               existing_type=postgresql.ENUM('open', 'accepted', 'rejected', 'expired', name='bidstatus'),
               nullable=True,
               existing_server_default=sa.text("'open'::bidstatus"))
    op.add_column('patients', sa.Column('consent_given', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_constraint('patients_email_hash_key', 'patients', type_='unique')
    op.alter_column('patients', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('patients', 'data_retention_days',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('365'))
    op.alter_column('patients', 'consent_research_sharing',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.add_column('orders', sa.Column('drug_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('stripe_pi_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('orders_patient_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key('orders_patient_id_fkey', 'orders', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.alter_column('orders', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('orders', 'amount_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('orders', 'status', existing_type=_ORDER_STATUS, server_default=None)
    op.alter_column('orders', 'status',
               existing_type=_ORDER_STATUS,
               type_=sa.VARCHAR(),
               postgresql_using='status::varchar',
               nullable=True)
    op.alter_column('orders', 'status', existing_type=sa.VARCHAR(), server_default=sa.text("'pending'::character varying"))
    op.alter_column('orders', 'drug_spec',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('oncologists', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('oncologists', 'verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('oncologists', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('oncologists', 'reports_reviewed')
    op.drop_column('oncologists', 'specialty')
    op.add_column('mutations', sa.Column('hgvs_c', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mutations', sa.Column('alphamissense_class', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mutations', sa.Column('variant', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mutations', sa.Column('civic_evidence', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('mutations', sa.Column('clinvar_significance', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mutations', sa.Column('consequence', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mutations', sa.Column('hgvs_p', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('mutations_submission_id_fkey', 'mutations', type_='foreignkey')
    op.create_foreign_key('mutations_submission_id_fkey', 'mutations', 'submissions', ['submission_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_mutations_submission_id', 'mutations', ['submission_id'], unique=False)
    op.create_index('ix_mutations_gene', 'mutations', ['gene'], unique=False)
    op.alter_column('mutations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('mutations', 'is_targetable',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('mutations', 'oncokb_level',
               existing_type=_ONCOKB_LEVEL,
               type_=sa.VARCHAR(),
               postgresql_using='oncokb_level::varchar',
               nullable=True)
    op.alter_column('mutations', 'gene',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('mutations', 'cosmic_id')
    op.drop_column('mutations', 'clinvar_id')
    op.drop_column('mutations', 'classification')
    op.create_index('ix_sig_submission_id', 'mutation_signatures', ['submission_id'], unique=False)
    op.alter_column('mutation_signatures', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('drug_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint('deletion_requests_patient_id_fkey', 'deletion_requests', type_='foreignkey')
    # String -> UUID needs an explicit cast (reverse of the upgrade() step).
    op.alter_column('deletion_requests', 'patient_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               postgresql_using='patient_id::uuid',
               existing_nullable=True)
    op.alter_column('deletion_requests', 'id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               postgresql_using='id::uuid',
               existing_nullable=False)
    op.create_index('ix_cna_submission_id', 'copy_number_alterations', ['submission_id'], unique=False)
    op.create_index('ix_cna_gene', 'copy_number_alterations', ['gene'], unique=False)
    op.alter_column('copy_number_alterations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index('ix_cohort_samples_study_id', 'cohort_samples', ['study_id'], unique=False)
    op.create_index('ix_cohort_samples_sample_id', 'cohort_samples', ['sample_id'], unique=False)
    op.alter_column('cohort_samples', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index('ix_cohort_mutations_study_id', 'cohort_mutations', ['study_id'], unique=False)
    op.create_index('ix_cohort_mutations_gene_protein', 'cohort_mutations', ['gene', 'protein_change'], unique=False)
    op.create_index('ix_cohort_mutations_gene', 'cohort_mutations', ['gene'], unique=False)
    op.alter_column('cohort_mutations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('campaigns', sa.Column('stripe_product_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('campaigns', sa.Column('submission_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('campaigns', sa.Column('percent_complete', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=True))
    op.drop_constraint('campaigns_order_id_fkey', 'campaigns', type_='foreignkey')
    op.drop_constraint('campaigns_patient_id_fkey', 'campaigns', type_='foreignkey')
    op.drop_constraint('campaigns_result_id_fkey', 'campaigns', type_='foreignkey')
    op.create_foreign_key('campaigns_submission_id_fkey', 'campaigns', 'submissions', ['submission_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('campaigns_patient_id_fkey', 'campaigns', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('campaigns_result_id_key', 'campaigns', type_='unique')
    op.alter_column('campaigns', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('campaigns', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('campaigns', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('campaigns', 'raised_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.create_table('repurposing_candidates',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('submission_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('drug_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('chembl_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mechanism', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('target_gene', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('binding_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('opentargets_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('oncokb_actionable', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('rank_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], name='repurposing_candidates_submission_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='repurposing_candidates_pkey')
    )
    op.create_index('ix_repurposing_submission_id', 'repurposing_candidates', ['submission_id'], unique=False)
    # ### end Alembic commands ###

    # Drop the 4 enum types created in upgrade(), now that no column uses them.
    bind = op.get_bind()
    _SUBMISSION_STATUS.drop(bind, checkfirst=True)
    _ORDER_STATUS.drop(bind, checkfirst=True)
    _ONCOKB_LEVEL.drop(bind, checkfirst=True)
    _MUTATION_CLASSIFICATION.drop(bind, checkfirst=True)
