apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "openoncology.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "openoncology.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
