"""
Notify Worker — all transactional email notifications.
Uses Resend for delivery. HTML generated by services/email_templates.py.

Tasks:
  notify_results_ready       — genomic results analysis finished
  notify_campaign_milestone  — campaign crosses 25/50/75/100% of goal
  notify_order_confirmed     — drug order payment confirmed
  notify_pharma_approved     — pharma company verified by admin
  notify_review_complete     — oncologist has reviewed a submission
"""
import logging

from workers import celery_app

logger = logging.getLogger(__name__)

_FROM = "OpenOncology <noreply@openoncology.org>"
_APP_URL = "https://openoncology.org"   # override via settings if needed


def _send(to_email: str, subject: str, html: str) -> None:
    """Send via Resend. Raises on failure so Celery can retry."""
    import resend
    from config import settings as _s

    resend.api_key = _s.resend_api_key
    resend.Emails.send({"from": _FROM, "to": to_email, "subject": subject, "html": html})


def _get_patient_email_from_keycloak(keycloak_id: str) -> str | None:
    """Retrieve patient email from Keycloak Admin API using service account."""
    import httpx
    from config import settings

    try:
        token_resp = httpx.post(
            f"{settings.keycloak_url}/realms/master/protocol/openid-connect/token",
            data={
                "client_id": "admin-cli",
                "grant_type": "password",
                "username": "admin",
                "password": getattr(settings, "keycloak_admin_password", ""),
            },
            timeout=5,
        )
        token = token_resp.json().get("access_token")
        if not token:
            return None

        user_resp = httpx.get(
            f"{settings.keycloak_url}/admin/realms/{settings.keycloak_realm}/users/{keycloak_id}",
            headers={"Authorization": f"Bearer {token}"},
            timeout=5,
        )
        user_resp.raise_for_status()
        return user_resp.json().get("email")

    except Exception as exc:
        logger.warning("[notify] Keycloak email lookup failed: %s", exc)
        return None


@celery_app.task(
    name="workers.notify_worker.notify_results_ready",
    bind=True,
    max_retries=3,
    default_retry_delay=30,
)
def notify_results_ready(self, submission_id: str, patient_id: str):
    from workers._db_sync import get_sync_session
    from models.patient import Patient
    from models.submission import Submission
    from models.mutation import Mutation
    from models.repurposing import RepurposingCandidate
    from sqlalchemy import select

    try:
        with get_sync_session() as db:
            submission = db.get(Submission, submission_id)
            patient = db.get(Patient, patient_id)
            if not submission or not patient:
                logger.warning("[notify] Missing submission/patient for %s", submission_id)
                return

            mutations = db.execute(
                select(Mutation).where(Mutation.submission_id == submission_id)
            ).scalars().all()
            targetable = [m for m in mutations if m.is_targetable]
            drugs = db.execute(
                select(RepurposingCandidate)
                .where(RepurposingCandidate.submission_id == submission_id)
                .order_by(RepurposingCandidate.rank_score.desc())
                .limit(3)
            ).scalars().all()
            top_drug_names = [d.drug_name for d in drugs if d.drug_name]

        email = _get_patient_email_from_keycloak(patient.keycloak_id)
        if not email:
            logger.warning("[notify] No email found for patient %s", patient_id)
            return

        from services.email_templates import render_results_ready
        subject, html = render_results_ready(
            submission_id=submission_id,
            mutation_count=len(mutations),
            targetable_count=len(targetable),
            top_drugs=top_drug_names,
            results_url=f"{_APP_URL}/results/{submission_id}",
        )
        _send(email, subject, html)
        logger.info("[notify] Results email sent for submission %s", submission_id)

    except Exception as exc:
        logger.error("[notify] notify_results_ready failed: %s", exc)
        raise self.retry(exc=exc)


@celery_app.task(
    name="workers.notify_worker.notify_campaign_milestone",
    bind=True,
    max_retries=3,
    default_retry_delay=30,
)
def notify_campaign_milestone(self, campaign_id: str, percent: int):
    from workers._db_sync import get_sync_session
    from models.campaign import Campaign
    from models.patient import Patient

    try:
        with get_sync_session() as db:
            campaign = db.get(Campaign, campaign_id)
            if not campaign:
                return
            patient = db.get(Patient, campaign.patient_id)

        if not patient:
            return

        email = _get_patient_email_from_keycloak(patient.keycloak_id)
        if not email:
            return

        from services.email_templates import render_campaign_milestone
        subject, html = render_campaign_milestone(
            campaign_title=campaign.title,
            percent=percent,
            raised_usd=float(campaign.raised_usd or 0),
            goal_usd=float(campaign.goal_usd),
            campaign_url=f"{_APP_URL}/crowdfund/{campaign.slug}",
        )
        _send(email, subject, html)
        logger.info("[notify] Milestone email (%d%%) sent for campaign %s", percent, campaign_id)

    except Exception as exc:
        logger.error("[notify] notify_campaign_milestone failed: %s", exc)
        raise self.retry(exc=exc)


@celery_app.task(
    name="workers.notify_worker.notify_order_confirmed",
    bind=True,
    max_retries=3,
    default_retry_delay=30,
)
def notify_order_confirmed(self, order_id: str):
    from workers._db_sync import get_sync_session
    from models.order import Order
    from models.patient import Patient
    from models.pharma import PharmaCompany

    try:
        with get_sync_session() as db:
            order = db.get(Order, order_id)
            if not order:
                return
            patient = db.get(Patient, order.patient_id)
            pharma = db.get(PharmaCompany, order.pharma_id)

        if not patient or not pharma:
            return

        email = _get_patient_email_from_keycloak(patient.keycloak_id)
        if not email:
            return

        from services.email_templates import render_order_confirmed
        subject, html = render_order_confirmed(
            order_id=str(order.id),
            drug_name=order.drug_name or "Drug treatment",
            pharma_name=pharma.name,
            amount_usd=float(order.amount_usd or 0),
            dashboard_url=f"{_APP_URL}/dashboard",
        )
        _send(email, subject, html)
        logger.info("[notify] Order confirmed email sent for order %s", order_id)

    except Exception as exc:
        logger.error("[notify] notify_order_confirmed failed: %s", exc)
        raise self.retry(exc=exc)


@celery_app.task(
    name="workers.notify_worker.notify_pharma_approved",
    bind=True,
    max_retries=3,
    default_retry_delay=30,
)
def notify_pharma_approved(self, pharma_id: str):
    from workers._db_sync import get_sync_session
    from models.pharma import PharmaCompany

    try:
        with get_sync_session() as db:
            pharma = db.get(PharmaCompany, pharma_id)
            if not pharma:
                return
            email = pharma.contact_email
            name = pharma.name

        onboarding_url = f"{_APP_URL}/pharma/onboarding?id={pharma_id}"

        from services.email_templates import render_pharma_approved
        subject, html = render_pharma_approved(
            company_name=name,
            onboarding_url=onboarding_url,
        )
        _send(email, subject, html)
        logger.info("[notify] Pharma approved email sent to %s", email)

    except Exception as exc:
        logger.error("[notify] notify_pharma_approved failed: %s", exc)
        raise self.retry(exc=exc)


@celery_app.task(
    name="workers.notify_worker.notify_review_complete",
    bind=True,
    max_retries=3,
    default_retry_delay=30,
)
def notify_review_complete(self, submission_id: str):
    from workers._db_sync import get_sync_session
    from models.result import Result
    from models.submission import Submission
    from models.patient import Patient

    try:
        with get_sync_session() as db:
            result = db.get(Result, submission_id)
            if not result:
                return
            submission = db.get(Submission, submission_id)
            if not submission:
                return
            patient = db.get(Patient, submission.patient_id)

        if not patient:
            return

        email = _get_patient_email_from_keycloak(patient.keycloak_id)
        if not email:
            return

        notes = result.oncologist_notes or ""
        approved = not notes.startswith("[FLAGGED]")
        clean_notes = notes.removeprefix("[FLAGGED] ")

        from services.email_templates import render_review_complete
        subject, html = render_review_complete(
            submission_id=submission_id,
            approved=approved,
            oncologist_notes=clean_notes,
            results_url=f"{_APP_URL}/results/{submission_id}",
        )
        _send(email, subject, html)
        logger.info("[notify] Review complete email sent for submission %s", submission_id)

    except Exception as exc:
        logger.error("[notify] notify_review_complete failed: %s", exc)
        raise self.retry(exc=exc)
